[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Redirecciones para enrutamiento basado en cliente (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeceras de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"